In [16]:
import pandas as pd

In [28]:
df = pd.read_csv("graph_data.csv")

{'ADA',
 'ALGO',
 'ATOM',
 'BCH',
 'BNB',
 'BSV',
 'BTC',
 'BUSD',
 'CRO',
 'CTC',
 'DAI',
 'DASH',
 'DOT',
 'EOS',
 'ETC',
 'ETH',
 'FTT',
 'HEDG',
 'HEX',
 'HT',
 'LEO',
 'LINK',
 'LTC',
 'MIOTA',
 'MKR',
 'NEO',
 'OKB',
 'OMG',
 'ONT',
 'SNX',
 'THETA',
 'TRX',
 'TUSD',
 'UMA',
 'USDC',
 'USDT',
 'VET',
 'WBTC',
 'XEM',
 'XLM',
 'XMR',
 'XRP',
 'XTZ',
 'YFI',
 'ZEC'}

In [18]:
for index, row in df.iterrows():
    print(row)

coinfrom    ADA
cointo      ADA
corr        1.0
Name: 0, dtype: object
coinfrom        ALGO
cointo           ADA
corr        0.553742
Name: 1, dtype: object
coinfrom        ATOM
cointo           ADA
corr        0.544778
Name: 2, dtype: object
coinfrom         BCH
cointo           ADA
corr        0.487691
Name: 3, dtype: object
coinfrom         BNB
cointo           ADA
corr        0.402013
Name: 4, dtype: object
coinfrom         BSV
cointo           ADA
corr        0.407859
Name: 5, dtype: object
coinfrom         BTC
cointo           ADA
corr        0.475343
Name: 6, dtype: object
coinfrom         CRO
cointo           ADA
corr        0.414101
Name: 7, dtype: object
coinfrom        DASH
cointo           ADA
corr        0.419372
Name: 8, dtype: object
coinfrom         DOT
cointo           ADA
corr        0.449677
Name: 9, dtype: object
coinfrom         EOS
cointo           ADA
corr        0.538506
Name: 10, dtype: object
coinfrom         ETC
cointo           ADA
corr        0.300966
Name: 11, dtype: object
coinfrom         ETH
cointo           ADA
corr        0.620004
Name: 12, dtype: object
coinfrom         FTT
cointo           ADA
corr        0.562476
Name: 13, dtype: object
coinfrom        HEDG
cointo           ADA
corr        0.200968
Name: 14, dtype: object
coinfrom         HT
cointo          ADA
corr        0.28631
Name: 15, dtype: object
coinfrom       LINK
cointo          ADA
corr        0.60222
Name: 16, dtype: object
coinfrom         LTC
cointo           ADA
corr        0.500781
Name: 17, dtype: object
coinfrom       MIOTA
cointo           ADA
corr        0.591896
Name: 18, dtype: object
coinfrom         MKR
cointo           ADA
corr        0.486807
Name: 19, dtype: object
coinfrom         NEO
cointo           ADA
corr        0.470273
Name: 20, dtype: object
coinfrom         OMG
cointo           ADA
corr        0.527971
Name: 21, dtype: object
coinfrom         ONT
cointo           ADA
corr        0.546932
Name: 22, dtype: object
coinfrom         SNX
cointo           ADA
corr        0.481501
Name: 23, dtype: object
coinfrom       THETA
cointo           ADA
corr        0.299222
Name: 24, dtype: object
coinfrom         TRX
cointo           ADA
corr        0.375572
Name: 25, dtype: object
coinfrom         UMA
cointo           ADA
corr        0.350993
Name: 26, dtype: object
coinfrom         VET
cointo           ADA
corr        0.522344
Name: 27, dtype: object
coinfrom        WBTC
cointo           ADA
corr        0.443124
Name: 28, dtype: object
coinfrom         XEM
cointo           ADA
corr        0.346858
Name: 29, dtype: object
coinfrom         XLM
cointo           ADA
corr        0.632769
Name: 30, dtype: object
coinfrom         XMR
cointo           ADA
corr        0.396095
Name: 31, dtype: object
coinfrom         XRP
cointo           ADA
corr        0.327184
Name: 32, dtype: object
coinfrom         XTZ
cointo           ADA
corr        0.600491
Name: 33, dtype: object
coinfrom         YFI
cointo           ADA
corr        0.361986
Name: 34, dtype: object
coinfrom         ZEC
cointo           ADA
corr        0.511259
Name: 35, dtype: object
coinfrom         ADA
cointo          ALGO
corr        0.553742
Name: 36, dtype: object
coinfrom    ALGO
cointo      ALGO
corr         1.0
Name: 37, dtype: object
coinfrom        ATOM
cointo          ALGO
corr        0.654622
Name: 38, dtype: object
coinfrom         BCH
cointo          ALGO
corr        0.535326
Name: 39, dtype: object
coinfrom         BNB
cointo          ALGO
corr        0.426836
Name: 40, dtype: object
coinfrom         BSV
cointo          ALGO
corr        0.490242
Name: 41, dtype: object
coinfrom        BTC
cointo         ALGO
corr        0.52306
Name: 42, dtype: object
coinfrom         CRO
cointo          ALGO
corr        0.366695
Name: 43, dtype: object
coinfrom        DASH
cointo          ALGO
corr        0.464585
Name: 44, dtype: object
coinfrom         DOT
cointo          ALGO
corr        0.490529
Name: 45, dtype: object
coinfrom        EOS
cointo         ALGO
corr        0.59295
Name: 46, dtype: object
coinfrom         ETC
cointo          ALGO
corr        0.370127
Name: 47, dtype: object
coinfrom         ETH
cointo          ALGO
corr        0.631836
Name: 48, dtype: object
coinfrom        FTT
cointo         ALGO
corr        0.55405
Name: 49, dtype: object
coinfrom        HEDG
cointo          ALGO
corr        0.241394
Name: 50, dtype: object
coinfrom          HT
cointo          ALGO
corr        0.368904
Name: 51, dtype: object
coinfrom        LINK
cointo          ALGO
corr        0.711225
Name: 52, dtype: object
coinfrom         LTC
cointo          ALGO
corr        0.567586
Name: 53, dtype: object
coinfrom       MIOTA
cointo          ALGO
corr        0.645424
Name: 54, dtype: object
coinfrom         MKR
cointo          ALGO
corr        0.480706
Name: 55, dtype: object
coinfrom         NEO
cointo          ALGO
corr        0.522355
Name: 56, dtype: object
coinfrom         OKB
cointo          ALGO
corr        0.299873
Name: 57, dtype: object
coinfrom         OMG
cointo          ALGO
corr        0.670322
Name: 58, dtype: object
coinfrom         ONT
cointo          ALGO
corr        0.684944
Name: 59, dtype: object
coinfrom         SNX
cointo          ALGO
corr        0.615641
Name: 60, dtype: object
coinfrom       THETA
cointo          ALGO
corr        0.446249
Name: 61, dtype: object
coinfrom         TRX
cointo          ALGO
corr        0.430514
Name: 62, dtype: object
coinfrom         UMA
cointo          ALGO
corr        0.431991
Name: 63, dtype: object
coinfrom         VET
cointo          ALGO
corr        0.653472
Name: 64, dtype: object
coinfrom        WBTC
cointo          ALGO
corr        0.491983
Name: 65, dtype: object
coinfrom         XEM
cointo          ALGO
corr        0.321743
Name: 66, dtype: object
coinfrom         XLM
cointo          ALGO
corr        0.566856
Name: 67, dtype: object
coinfrom        XMR
cointo         ALGO
corr        0.46554
Name: 68, dtype: object
coinfrom         XRP
cointo          ALGO
corr        0.418992
Name: 69, dtype: object
coinfrom         XTZ
cointo          ALGO
corr        0.772227
Name: 70, dtype: object
coinfrom         YFI
cointo          ALGO
corr        0.440283
Name: 71, dtype: object
coinfrom         ZEC
cointo          ALGO
corr        0.585902
Name: 72, dtype: object
coinfrom         ADA
cointo          ATOM
corr        0.544778
Name: 73, dtype: object
coinfrom        ALGO
cointo          ATOM
corr        0.654622
Name: 74, dtype: object
coinfrom    ATOM
cointo      ATOM
corr         1.0
Name: 75, dtype: object
coinfrom         BCH
cointo          ATOM
corr        0.463566
Name: 76, dtype: object
coinfrom        BNB
cointo         ATOM
corr        0.37025
Name: 77, dtype: object
coinfrom         BSV
cointo          ATOM
corr        0.426185
Name: 78, dtype: object
coinfrom         BTC
cointo          ATOM
corr        0.404294
Name: 79, dtype: object
coinfrom         CRO
cointo          ATOM
corr        0.329515
Name: 80, dtype: object
coinfrom        DASH
cointo          ATOM
corr        0.457687
Name: 81, dtype: object
coinfrom         DOT
cointo          ATOM
corr        0.494111
Name: 82, dtype: object
coinfrom         EOS
cointo          ATOM
corr        0.521138
Name: 83, dtype: object
coinfrom         ETC
cointo          ATOM
corr        0.251971
Name: 84, dtype: object
coinfrom         ETH
cointo          ATOM
corr        0.534081
Name: 85, dtype: object
coinfrom         FTT
cointo          ATOM
corr        0.495085
Name: 86, dtype: object
coinfrom        HEDG
cointo          ATOM
corr        0.213997
Name: 87, dtype: object
coinfrom          HT
cointo          ATOM
corr        0.308707
Name: 88, dtype: object
coinfrom        LINK
cointo          ATOM
corr        0.602376
Name: 89, dtype: object
coinfrom         LTC
cointo          ATOM
corr        0.443702
Name: 90, dtype: object
coinfrom      MIOTA
cointo         ATOM
corr        0.54908
Name: 91, dtype: object
coinfrom         MKR
cointo          ATOM
corr        0.423497
Name: 92, dtype: object
coinfrom         NEO
cointo          ATOM
corr        0.428649
Name: 93, dtype: object
coinfrom         OKB
cointo          ATOM
corr        0.205357
Name: 94, dtype: object
coinfrom         OMG
cointo          ATOM
corr        0.584395
Name: 95, dtype: object
coinfrom         ONT
cointo          ATOM
corr        0.553564
Name: 96, dtype: object
coinfrom         SNX
cointo          ATOM
corr        0.491969
Name: 97, dtype: object
coinfrom       THETA
cointo          ATOM
corr        0.341581
Name: 98, dtype: object
coinfrom         TRX
cointo          ATOM
corr        0.306626
Name: 99, dtype: object
coinfrom        UMA
cointo         ATOM
corr        0.34411
Name: 100, dtype: object
coinfrom         VET
cointo          ATOM
corr        0.567286
Name: 101, dtype: object
coinfrom        WBTC
cointo          ATOM
corr        0.373361
Name: 102, dtype: object
coinfrom         XEM
cointo          ATOM
corr        0.297662
Name: 103, dtype: object
coinfrom         XLM
cointo          ATOM
corr        0.463876
Name: 104, dtype: object
coinfrom         XMR
cointo          ATOM
corr        0.416081
Name: 105, dtype: object
coinfrom       XRP
cointo        ATOM
corr        0.2947
Name: 106, dtype: object
coinfrom         XTZ
cointo          ATOM
corr        0.665313
Name: 107, dtype: object
coinfrom         YFI
cointo          ATOM
corr        0.349297
Name: 108, dtype: object
coinfrom         ZEC
cointo          ATOM
corr        0.588854
Name: 109, dtype: object
coinfrom         ADA
cointo           BCH
corr        0.487691
Name: 110, dtype: object
coinfrom        ALGO
cointo           BCH
corr        0.535326
Name: 111, dtype: object
coinfrom        ATOM
cointo           BCH
corr        0.463566
Name: 112, dtype: object
coinfrom    BCH
cointo      BCH
corr        1.0
Name: 113, dtype: object
coinfrom         BNB
cointo           BCH
corr        0.402873
Name: 114, dtype: object
coinfrom         BSV
cointo           BCH
corr        0.858435
Name: 115, dtype: object
coinfrom         BTC
cointo           BCH
corr        0.612306
Name: 116, dtype: object
coinfrom         CRO
cointo           BCH
corr        0.410402
Name: 117, dtype: object
coinfrom        DASH
cointo           BCH
corr        0.710803
Name: 118, dtype: object
coinfrom         DOT
cointo           BCH
corr        0.387247
Name: 119, dtype: object
coinfrom         EOS
cointo           BCH
corr        0.779324
Name: 120, dtype: object
coinfrom         ETC
cointo           BCH
corr        0.642768
Name: 121, dtype: object
coinfrom         ETH
cointo           BCH
corr        0.705503
Name: 122, dtype: object
coinfrom         FTT
cointo           BCH
corr        0.563661
Name: 123, dtype: object
coinfrom        HEDG
cointo           BCH
corr        0.225956
Name: 124, dtype: object
coinfrom          HT
cointo           BCH
corr        0.392828
Name: 125, dtype: object
coinfrom        LINK
cointo           BCH
corr        0.653795
Name: 126, dtype: object
coinfrom         LTC
cointo           BCH
corr        0.763139
Name: 127, dtype: object
coinfrom       MIOTA
cointo           BCH
corr        0.705124
Name: 128, dtype: object
coinfrom         MKR
cointo           BCH
corr        0.484941
Name: 129, dtype: object
coinfrom         NEO
cointo           BCH
corr        0.659636
Name: 130, dtype: object
coinfrom         OKB
cointo           BCH
corr        0.274795
Name: 131, dtype: object
coinfrom         OMG
cointo           BCH
corr        0.622522
Name: 132, dtype: object
coinfrom         ONT
cointo           BCH
corr        0.701453
Name: 133, dtype: object
coinfrom        SNX
cointo          BCH
corr        0.43587
Name: 134, dtype: object
coinfrom       THETA
cointo           BCH
corr        0.403517
Name: 135, dtype: object
coinfrom         TRX
cointo           BCH
corr        0.494108
Name: 136, dtype: object
coinfrom        UMA
cointo          BCH
corr        0.35536
Name: 137, dtype: object
coinfrom         VET
cointo           BCH
corr        0.666294
Name: 138, dtype: object
coinfrom        WBTC
cointo           BCH
corr        0.568708
Name: 139, dtype: object
coinfrom         XEM
cointo           BCH
corr        0.229452
Name: 140, dtype: object
coinfrom         XLM
cointo           BCH
corr        0.552555
Name: 141, dtype: object
coinfrom         XMR
cointo           BCH
corr        0.537358
Name: 142, dtype: object
coinfrom         XRP
cointo           BCH
corr        0.463538
Name: 143, dtype: object
coinfrom         XTZ
cointo           BCH
corr        0.700149
Name: 144, dtype: object
coinfrom         YFI
cointo           BCH
corr        0.381905
Name: 145, dtype: object
coinfrom         ZEC
cointo           BCH
corr        0.702185
Name: 146, dtype: object
coinfrom         ADA
cointo           BNB
corr        0.402013
Name: 147, dtype: object
coinfrom        ALGO
cointo           BNB
corr        0.426836
Name: 148, dtype: object
coinfrom       ATOM
cointo          BNB
corr        0.37025
Name: 149, dtype: object
coinfrom         BCH
cointo           BNB
corr        0.402873
Name: 150, dtype: object
coinfrom    BNB
cointo      BNB
corr        1.0
Name: 151, dtype: object
coinfrom         BSV
cointo           BNB
corr        0.356966
Name: 152, dtype: object
coinfrom         BTC
cointo           BNB
corr        0.478419
Name: 153, dtype: object
coinfrom         CRO
cointo           BNB
corr        0.389815
Name: 154, dtype: object
coinfrom        DASH
cointo           BNB
corr        0.445765
Name: 155, dtype: object
coinfrom         DOT
cointo           BNB
corr        0.337012
Name: 156, dtype: object
coinfrom         EOS
cointo           BNB
corr        0.472698
Name: 157, dtype: object
coinfrom         ETC
cointo           BNB
corr        0.273061
Name: 158, dtype: object
coinfrom       ETH
cointo         BNB
corr        0.4592
Name: 159, dtype: object
coinfrom         FTT
cointo           BNB
corr        0.773271
Name: 160, dtype: object
coinfrom          HT
cointo           BNB
corr        0.802191
Name: 161, dtype: object
coinfrom         LEO
cointo           BNB
corr        0.265348
Name: 162, dtype: object
coinfrom        LINK
cointo           BNB
corr        0.463126
Name: 163, dtype: object
coinfrom         LTC
cointo           BNB
corr        0.443926
Name: 164, dtype: object
coinfrom       MIOTA
cointo           BNB
corr        0.477222
Name: 165, dtype: object
coinfrom         MKR
cointo           BNB
corr        0.328575
Name: 166, dtype: object
coinfrom         NEO
cointo           BNB
corr        0.479299
Name: 167, dtype: object
coinfrom         OKB
cointo           BNB
corr        0.716792
Name: 168, dtype: object
coinfrom         OMG
cointo           BNB
corr        0.410613
Name: 169, dtype: object
coinfrom        ONT
cointo          BNB
corr        0.44394
Name: 170, dtype: object
coinfrom         SNX
cointo           BNB
corr        0.378248
Name: 171, dtype: object
coinfrom       THETA
cointo           BNB
corr        0.228373
Name: 172, dtype: object
coinfrom        TRX
cointo          BNB
corr        0.34876
Name: 173, dtype: object
coinfrom         UMA
cointo           BNB
corr        0.293308
Name: 174, dtype: object
coinfrom         VET
cointo           BNB
corr        0.379069
Name: 175, dtype: object
coinfrom        WBTC
cointo           BNB
corr        0.442955
Name: 176, dtype: object
coinfrom         XEM
cointo           BNB
corr        0.283191
Name: 177, dtype: object
coinfrom         XLM
cointo           BNB
corr        0.348645
Name: 178, dtype: object
coinfrom         XMR
cointo           BNB
corr        0.454765
Name: 179, dtype: object
coinfrom         XRP
cointo           BNB
corr        0.307737
Name: 180, dtype: object
coinfrom         XTZ
cointo           BNB
corr        0.497538
Name: 181, dtype: object
coinfrom         YFI
cointo           BNB
corr        0.282462
Name: 182, dtype: object
coinfrom         ZEC
cointo           BNB
corr        0.482288
Name: 183, dtype: object
coinfrom         ADA
cointo           BSV
corr        0.407859
Name: 184, dtype: object
coinfrom        ALGO
cointo           BSV
corr        0.490242
Name: 185, dtype: object
coinfrom        ATOM
cointo           BSV
corr        0.426185
Name: 186, dtype: object
coinfrom         BCH
cointo           BSV
corr        0.858435
Name: 187, dtype: object
coinfrom         BNB
cointo           BSV
corr        0.356966
Name: 188, dtype: object
coinfrom    BSV
cointo      BSV
corr        1.0
Name: 189, dtype: object
coinfrom         BTC
cointo           BSV
corr        0.511147
Name: 190, dtype: object
coinfrom         CRO
cointo           BSV
corr        0.379877
Name: 191, dtype: object
coinfrom        DASH
cointo           BSV
corr        0.609842
Name: 192, dtype: object
coinfrom         DOT
cointo           BSV
corr        0.331757
Name: 193, dtype: object
coinfrom         EOS
cointo           BSV
corr        0.793906
Name: 194, dtype: object
coinfrom         ETC
cointo           BSV
corr        0.531307
Name: 195, dtype: object
coinfrom         ETH
cointo           BSV
corr        0.572287
Name: 196, dtype: object
coinfrom         FTT
cointo           BSV
corr        0.460101
Name: 197, dtype: object
coinfrom          HT
cointo           BSV
corr        0.379495
Name: 198, dtype: object
coinfrom        LINK
cointo           BSV
corr        0.575815
Name: 199, dtype: object
coinfrom         LTC
cointo           BSV
corr        0.657824
Name: 200, dtype: object
coinfrom       MIOTA
cointo           BSV
corr        0.637673
Name: 201, dtype: object
coinfrom         MKR
cointo           BSV
corr        0.504545
Name: 202, dtype: object
coinfrom         NEO
cointo           BSV
corr        0.511147
Name: 203, dtype: object
coinfrom         OKB
cointo           BSV
corr        0.289839
Name: 204, dtype: object
coinfrom         OMG
cointo           BSV
corr        0.575813
Name: 205, dtype: object
coinfrom         ONT
cointo           BSV
corr        0.645521
Name: 206, dtype: object
coinfrom         SNX
cointo           BSV
corr        0.408886
Name: 207, dtype: object
coinfrom       THETA
cointo           BSV
corr        0.378104
Name: 208, dtype: object
coinfrom         TRX
cointo           BSV
corr        0.487234
Name: 209, dtype: object
coinfrom         UMA
cointo           BSV
corr        0.310529
Name: 210, dtype: object
coinfrom         VET
cointo           BSV
corr        0.537575
Name: 211, dtype: object
coinfrom        WBTC
cointo           BSV
corr        0.479631
Name: 212, dtype: object
coinfrom         XEM
cointo           BSV
corr        0.231226
Name: 213, dtype: object
coinfrom         XLM
cointo           BSV
corr        0.476609
Name: 214, dtype: object
coinfrom         XMR
cointo           BSV
corr        0.449047
Name: 215, dtype: object
coinfrom         XRP
cointo           BSV
corr        0.414961
Name: 216, dtype: object
coinfrom         XTZ
cointo           BSV
corr        0.638706
Name: 217, dtype: object
coinfrom         YFI
cointo           BSV
corr        0.339537
Name: 218, dtype: object
coinfrom         ZEC
cointo           BSV
corr        0.616234
Name: 219, dtype: object
coinfrom         ADA
cointo           BTC
corr        0.475343
Name: 220, dtype: object
coinfrom       ALGO
cointo          BTC
corr        0.52306
Name: 221, dtype: object
coinfrom        ATOM
cointo           BTC
corr        0.404294
Name: 222, dtype: object
coinfrom         BCH
cointo           BTC
corr        0.612306
Name: 223, dtype: object
coinfrom         BNB
cointo           BTC
corr        0.478419
Name: 224, dtype: object
coinfrom         BSV
cointo           BTC
corr        0.511147
Name: 225, dtype: object
coinfrom    BTC
cointo      BTC
corr        1.0
Name: 226, dtype: object
coinfrom         CRO
cointo           BTC
corr        0.504893
Name: 227, dtype: object
coinfrom        DASH
cointo           BTC
corr        0.529747
Name: 228, dtype: object
coinfrom         DOT
cointo           BTC
corr        0.463986
Name: 229, dtype: object
coinfrom         EOS